<?php

function cptui_register_my_cpts_voz() {

	/**
	 * Post Type: Vozes.
	 */

	$labels = array(
		"name" => __( "Vozes", "voices" ),
		"singular_name" => __( "Voz", "voices" ),
		"add_new" => __( "Adicionar nova voz", "voices" ),
		"add_new_item" => __( "Adicionar nova voz", "voices" ),
		"edit_item" => __( "Editar voz", "voices" ),
		"new_item" => __( "Nova voz", "voices" ),
	);

	$args = array(
		"label" => __( "Vozes", "voices" ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"delete_with_user" => false,
		"show_in_rest" => true,
		"rest_base" => "",
		"rest_controller_class" => "WP_REST_Posts_Controller",
		"has_archive" => false,
		"show_in_menu" => false,
		"show_in_nav_menus" => true,
		"exclude_from_search" => false,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "voz", "with_front" => true ),
		"query_var" => true,
		"taxonomies" => array( "category", "post_tag" ),
	);

	register_post_type( "voz", $args );
}

add_action( 'init', 'cptui_register_my_cpts_voz' );


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c76c7ce83b56',
	'title' => __( "Atributos de Voz", "voices" ),
	'fields' => array(
		array(
			'key' => 'field_5c76ca0fff41f',
			'label' => __( "Nome", "voices" ),
			'name' => 'nome',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5c76c7ebac5da',
			'label' => __( "Gênero", "voices" ),
			'name' => 'genero',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Feminino' => __( "Feminino", "voices" ),
				'Masculino' => __( "Masculino", "voices" ),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5c76c831ac5db',
			'label' => __( "Idades", "voices" ),
			'name' => 'idades',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'10-15' => '10-15',
				'16-25' => '16-25',
				'26-40' => '26-40',
				'41-65' => '41-65',
				'66' => '66+',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c76ca2eff420',
			'label' => __( "Linguagens", "voices" ),
			'name' => 'linguagens',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Espanhol' => __( "Espanhol", "voices" ),
				'Francês' => __( "Francês", "voices" ),
				'Inglês UK' => __( "Inglês UK", "voices" ),
				'Inglês USA' => __( "Inglês USA", "voices" ),
				'Italiano' => __( "Italiano", "voices" ),
				'Japonês' => __( "Japonês", "voices" ),
				'Mandarim' => __( "Mandarim", "voices" ),
				'Português' => __( "Português", "voices" ),
				'Português do Brasil' => __( "Português do Brasil", "voices" ),
				'Alemão' => __( "Alemão", "voices" ),
				'Angolano' => __( "Angolano", "voices" ),
				'Outro' => __( "Outro", "voices" ),
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5c7d92ca4f242',
			'label' => __( "Biografia", "voices" ),
			'name' => 'biografia',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5c76caaeff421',
			'label' => __( "Comercial", "voices" ),
			'name' => 'comercial',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp3',
		),
		array(
			'key' => 'field_5c76cb2404e83',
			'label' => __( "Informativo", "voices" ),
			'name' => 'informativo',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp3',
		),
		array(
			'key' => 'field_5c76cb2304e82',
			'label' => __( "Institucional", "voices" ),
			'name' => 'personagem',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp3',
		),
		array(
			'key' => 'field_5c76cb2104e81',
			'label' => __( "Vídeo", "voices" ),
			'name' => 'video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'mp4',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'voz',
			),
		),
	),
	'menu_order' => -1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
?>